name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: false
          python-version: 3.8
      - name: install deps
        shell: bash -l {0}
        run: conda install numpy pytest
      - name: run grading
        shell: bash -l {0}
        run: which python && conda list
